# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [18]:
a_tr = np.transpose(a)
a_mul = np.dot(a, a_tr)
a_mul

array([[1.57995312, 0.48673782, 1.28525324, 0.9947397 , 0.64675177],
       [0.48673782, 0.40706809, 0.26368252, 0.57840584, 0.55984141],
       [1.28525324, 0.26368252, 1.11497408, 0.64198458, 0.34157207],
       [0.9947397 , 0.57840584, 0.64198458, 1.44251562, 0.77015453],
       [0.64675177, 0.55984141, 0.34157207, 0.77015453, 0.77110897]])

In [19]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
tensor([0.6857, 0.3036, 0.5085, 0.5662, 0.4089], dtype=torch.float64)



In [20]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
torch.Size([3, 5])



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [21]:
sm = np.sum(i * i for i in range(1, 10001))
sm

<ipython-input-21-8863e6edf9cf>:1: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  sm = np.sum(i * i for i in range(1, 10001))


333383335000

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [22]:
x = torch.rand(5, 3)
x

tensor([[0.4150, 0.5029, 0.1343],
        [0.3306, 0.8078, 0.1557],
        [0.6210, 0.5751, 0.5058],
        [0.2983, 0.0304, 0.9939],
        [0.1101, 0.7748, 0.3981]])

In [23]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [24]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.4150, 5.5029, 5.1343],
        [5.3306, 5.8078, 5.1557],
        [5.6210, 5.5751, 5.5058],
        [5.2983, 5.0304, 5.9939],
        [5.1101, 5.7748, 5.3981]])



In [25]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[0.4432, 0.5644, 0.6149, 0.2726, 0.4888],
        [0.5644, 0.7861, 0.7487, 0.2780, 0.7243],
        [0.6149, 0.7487, 0.9723, 0.7055, 0.7154],
        [0.2726, 0.2780, 0.7055, 1.0778, 0.4521],
        [0.4888, 0.7243, 0.7154, 0.4521, 0.7709]])

X*X^T  (2):
tensor([[0.4432, 0.5644, 0.6149, 0.2726, 0.4888],
        [0.5644, 0.7861, 0.7487, 0.2780, 0.7243],
        [0.6149, 0.7487, 0.9723, 0.7055, 0.7154],
        [0.2726, 0.2780, 0.7055, 1.0778, 0.4521],
        [0.4888, 0.7243, 0.7154, 0.4521, 0.7709]])



In [26]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.3507, 0.4314, 0.5673, 0.4409, 0.4277])



In [27]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [28]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-28-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [29]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[ 7.1862e+04,  3.2065e-41,  1.2747e+03],
        [ 3.2065e-41, -7.7205e-32,  4.5551e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [30]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.0340, 0.8710, 0.4144],
        [0.3704, 0.2285, 0.2255],
        [0.2757, 0.0540, 0.8350],
        [0.3451, 0.8649, 0.1400],
        [0.0331, 0.0929, 0.7011]])


In [31]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [32]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [33]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [34]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[-0.0616,  0.6607,  0.6409],
        [ 1.5571,  0.7016,  1.2772],
        [-0.9704, -1.8336,  0.6272],
        [-0.5999,  0.9844,  0.7073],
        [ 0.6967,  0.5039, -0.7998]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [36]:
torch.manual_seed(42)

x = torch.rand(5, 3)
y = torch.rand(5, 3)
sm = x + y
sm

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])

In [37]:
print(x * y) # поэлементное умножение

tensor([[0.3789, 0.8102, 0.2197],
        [0.2557, 0.2450, 0.1620],
        [0.1132, 0.2356, 0.7824],
        [0.0140, 0.2519, 0.2130],
        [0.1733, 0.3106, 0.0046]])


## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [42]:
y_tr = torch.transpose(y, 0, 1)
print(x.mm(y_tr))

tensor([[1.4088, 0.9125, 0.9795, 0.4769, 0.6789],
        [1.1025, 0.6627, 1.0391, 0.4219, 0.4086],
        [1.3528, 0.8200, 1.1313, 0.5785, 0.4912],
        [1.2254, 0.7820, 0.8300, 0.4789, 0.5416],
        [1.3013, 0.7878, 1.1686, 0.5105, 0.4885]])


In [43]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга

torch.Size([1, 5, 3])


In [44]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга

torch.Size([5, 3])


In [45]:
a = torch.rand((1,3))
a

tensor([[0.9516, 0.0753, 0.8860]])

In [46]:
a.squeeze(0)

tensor([0.9516, 0.0753, 0.8860])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [47]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [48]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [49]:
a @ b

array([70])

In [50]:
b @ a

ValueError: ignored