In [ ]:
import torch
import numpy as np
import pandas as pd

Данная строка кода создает тензор в библиотеке PyTorch.

**torch.tensor()** - это функция для создания тензора. В данном случае, передаваемый аргумент [[1., -1.], [1., -1.]] представляет собой двумерный массив/список, содержащий значения для инициализации тензора.

In [ ]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

Эта строка кода создает тензор в библиотеке PyTorch, используя функцию torch.tensor(). В данном случае, в качестве аргумента передается результат преобразования массива NumPy в тензор.

In [ ]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

Данная строка кода выполняет преобразование массива NumPy в тензор PyTorch.

In [ ]:
torch.from_numpy(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

Данная строка кода создает тензор PyTorch размером 2x4, заполненный нулями и с типом данных torch.complex32.

In [ ]:
torch.zeros([2, 4], dtype=torch.complex32)

<ipython-input-5-36c2eba0da08>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:31.)
  torch.zeros([2, 4], dtype=torch.complex32)


tensor([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=torch.complex32)

Данная строка кода создает тензор PyTorch размером 2x4, заполненный единицами и с типом данных torch.int64.

In [ ]:
torch.ones([2, 4], dtype=torch.int64)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

Данная строка кода создает единичную матрицу (или матрицу единичного соотношения) размером 5x5 с использованием библиотеки PyTorch.

torch.eye() используется для создания единичной матрицы с размерами, заданными аргументом. В данном случае, аргумент 5 указывает на размеры матрицы - 5 строк и 5 столбцов.

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Данная строка кода используется для проверки наличия и доступности GPU (графического процессора) для вычислений с помощью библиотеки PyTorch.

Метод torch.cuda.is_available() возвращает булево значение (True или False) в зависимости от того, доступно ли GPU для использования.

Если возвращается значение True, это означает, что у вас установлен и доступен GPU, и вы можете использовать его для ускорения вычислений в PyTorch. Если возвращается значение False, это означает, что либо у вас нет GPU, либо оно не доступно для использования в данный момент.

In [ ]:
torch.cuda.is_available()

False

Данная строка кода используется для выбора устройства (device) для выполнения вычислений в PyTorch, в зависимости от доступности и возможности использования графического процессора (GPU).

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
A = torch.tensor([[1., -1.], [1., -1.]])

Данная строка кода выполняет операцию переноса (move) объекта A на определенное устройство (device) в PyTorch.

В PyTorch, устройство (device) может быть 'cuda' для использования графического процессора (GPU) или 'cpu' для использования центрального процессора (CPU).

Функция to(device) позволяет изменять расположение (device) тензора или модели PyTorch. При выполнении операции A.to(device), тензор или модель A будет перемещен(а) на указанное устройство (device).

In [ ]:
A.to(device)

tensor([[ 1., -1.],
        [ 1., -1.]])

In [ ]:
device = 'cpu'

In [ ]:
a = torch.Tensor([1,2,3])

In [ ]:
a.to(device)

tensor([1., 2., 3.])

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[0][1],'\n\n')

x[0][1] = 8
print(x)

tensor(2) 


tensor([[1, 8, 3],
        [4, 5, 6]])


In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
x = torch.tensor([[1]])
int(x[0][0])

1

Данная строка кода возвращает скалярное значение (тип данных Python) из тензора x в PyTorch.

В PyTorch, тензоры могут содержать как многомерные массивы значений (например, матрицы), так и скалярные значения (единичные числа). Метод item() применяется к тензору x и извлекает его значение как обычное число в Python. Если x содержит более одного элемента, то item() вернет только первый элемент тензора.

In [ ]:
x.item()

1

Данный код выполняет вычисление градиента функции от переменной x в PyTorch, используя автоматическое дифференцирование.

В первой строке создается тензор x размером 2x2 с указанными значениями. Параметр requires_grad=True указывает, что мы хотим вычислить градиенты этого тензора в отношении других тензоров или скаляров.

Во второй строке вычисляется функция out, которая является результатом возведения элементов тензора x в квадрат и их суммирования. Это выражение можно записать как: out = x[0,0]^2 + x[0,1]^2 + x[1,0]^2 + x[1,1]^2.

В третьей строке вызывается метод backward(), который инициирует обратное распространение ошибки (backpropagation) и вычисляет градиенты всех тензоров с параметром requires_grad=True относительно out.

В последней строке кода x.grad возвращает вычисленные градиенты функции out по отношению к x. Градиенты сохраняются в атрибуте grad объекта x.

In [ ]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

Данная строка кода выполняет операцию возведения в квадрат каждого элемента тензора x.

In [ ]:
x.pow(2)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

Данный код создает новый тензор на основе data и присваивает его переменной tensor.

tensor.new_tensor(data) создает новый тензор на основе data с теми же типом данных и устройством памяти, что и у исходного тензора tensor. Это позволяет создать новый тензор с такими же характеристиками, но с другими значениями.

В данном случае, исходный тензор tensor инициализируется с помощью функции torch.ones с размерностью (2,) и типом данных torch.int8. Затем, с использованием метода new_tensor, создается новый тензор с данными из data.

In [ ]:
tensor = torch.ones((2,), dtype=torch.int8)
data = [[0, 1], [2, 3]]
tensor.new_tensor(data)

tensor([[0, 1],
        [2, 3]], dtype=torch.int8)

Копирование тензоров производится функцией tensor.clone()

In [ ]:
a = torch.tensor([[2,1,3],[3,2,1],[5,4,2]])
b = a.clone()

 Продифференцируем функцию u(x,y) = x^2 + y^2 -x - y

Данный код выполняет следующие действия:

Создает два тензора x и y с одним элементом [4.] и [2.] соответственно. Оба тензора имеют установленный флаг requires_grad = True, что указывает на то, что необходимо вычислять градиенты по этим тензорам в процессе обратного распространения ошибки.

Создает переменные x и y с помощью класса Variable из модуля torch.autograd. Это старая версия использования градиентов в PyTorch, и сейчас рекомендуется использовать просто тензоры с флагом requires_grad = True.

Выполняет вычисление функции u, которая является результатом вычисления выражения x^2 + y^2 - x - y.

Вызывает метод backward() для тензора u для вычисления градиентов по x и y. Флаг retain_graph=True указывает на то, что граф вычислений должен быть сохранен, чтобы можно было вычислить градиенты в следующих строках кода.

Выводит градиенты x.grad и y.grad.

Обнуляет градиенты тензоров x и y с помощью метода zero_().

Создает тензор a размером (2, 2) со случайными значениями, а затем выполняет вычисления над ним, включающие умножение на 3, деление на (a - 1). Флаг requires_grad для a сначала равен False, но после вызова requires_grad_(True) он устанавливается на True.

Вычисляет b как сумму элементов a в квадрате.

Выводит информацию о градиентной функции b.grad_fn, которая отображает примененную операцию для получения b.

Создает тензор x размером (2, 2) из единиц с установленным флагом requires_grad=True.

Выполняет операцию y = x + 2.

Выполняет операцию z = y * y * 3.

Выполняет операцию out = z.mean() - вычисление среднего значения элементов z.

Вызывает метод backward() для тензора out для вычисления градиентов по x.

Выводит градиенты x.grad.

In [ ]:
x = torch.tensor([4.], requires_grad = True)
y = torch.tensor([2.], requires_grad = True)

from torch.autograd import Variable
x = Variable(x, requires_grad = True)
y = Variable(y, requires_grad = True)

u = torch.pow(x,2) +  torch.pow(y,2) - x - y

u.backward(retain_graph=True)
print('gradient of x: {}'.format(x.grad), '\n gradient of y: {}'.format(y.grad))

x.grad.data.zero_()
y.grad.data.zero_()

a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

gradient of x: tensor([7.]) 
 gradient of y: tensor([3.])
False
True
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


Данный код выполняет следующие действия:

Печатает значение свойства requires_grad для тензора x. Свойство requires_grad указывает, следует ли вычислять градиенты для данного тензора при выполнении операций с ним. Значение True означает, что градиенты будут вычисляться, а значение False означает, что градиенты не будут вычисляться.

Создает новый тензор y с помощью метода detach() от тензора x. Метод detach() создает новый тензор, который является копией x, но не связан с графом вычислений. Это означает, что градиенты не будут вычисляться для y и он будет являться отдельным от x тензором.

Печатает значение свойства requires_grad для тензора y. Здесь значение должно быть False, так как y был создан с отключенным вычислением градиентов при отделении его от x с помощью detach().

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


## Методы view(), cat()

In [ ]:
tensor = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])

Метод **view()** используется для изменения формы тензора, чтобы он соответствовал новым размерам, указанным в аргументе.

Данная строчка кода выполняет операцию изменения размерности (reshaping) для тензора tensor

In [ ]:
tensor.view(-1)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Когда аргументы заданы как 1,-1, это означает, что мы хотим изменить форму тензора на такую, где первое измерение имеет размер 1 (то есть будет добавлено одно измерение), а размер второго измерения рассчитывается автоматически на основе общего количества элементов в тензоре, чтобы поддерживать согласованность.

Таким образом, tensor.view(1,-1) преобразует тензор tensor в новую форму, где он будет иметь размерность (1, N), где N - это автоматически вычисленный размер второго измерения. Это может быть полезно, например, при решении задач, где ожидается ввод тензора определенного размера или формы, или для операций, требующих конкретной размерности.

In [ ]:
tensor.view(1,-1)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Когда аргумент -1 используется в методе view(), это означает, что размер этого измерения должен быть вычислен автоматически. Таким образом, -1, 1 указывает на новую форму тензора, где первое измерение будет иметь неопределенный размер (размер будет вычислен автоматически), а второе измерение будет иметь размер 1.

Итак, tensor.view(-1, 1) изменяет форму тензора tensor на новую форму, где он будет иметь размерность (N, 1), где N - это автоматически вычисленный размер первого измерения. Это может быть полезно, например, при решении задач, где ожидается вывод тензора с определенной размерностью или формой, или для операций, требующих конкретной размерности.

In [ ]:
tensor.view(-1,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
tensor2 = torch.FloatTensor([[10,11,12]])

Данная строка кода выполняет операцию конкатенации (объединения) двух тензоров tensor и tensor2 вдоль указанного измерения dim=0.

Метод torch.cat() используется для объединения (конкатенации) тензоров вдоль указанной оси (измерения). В данном случае, tensor и tensor2 являются аргументами метода torch.cat(), а dim=0 указывает на ось, вдоль которой будет выполняться объединение.

In [ ]:
Tensor = torch.cat((tensor,tensor2), dim=0)

In [ ]:
Tensor2 = Tensor.new_full((4,3),3)
Tensor2

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [ ]:
TENSOR = torch.cat((Tensor,Tensor2),axis = 0)
TENSOR

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.]])

In [ ]:
TENSOR = torch.cat((Tensor,Tensor2),axis = 1)
TENSOR

tensor([[ 1.,  2.,  3.,  3.,  3.,  3.],
        [ 4.,  5.,  6.,  3.,  3.,  3.],
        [ 7.,  8.,  9.,  3.,  3.,  3.],
        [10., 11., 12.,  3.,  3.,  3.]])

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.cat((a,b), dim=0)

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
torch.stack((a,b), dim=1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Избежание популярной ошибки

In [ ]:
a = torch.ones((1,3))
b = torch.zeros(4)
c = torch.cat((a,b.view(1,-1)),axis = 1)

# Модуль nn и создание моделей

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd

Данная строка кода определяет архитектуру нейронной сети (NN) с использованием модулей из библиотеки PyTorch.

С помощью nn.Sequential() создается последовательное соединение нескольких слоев (модулей), где вывод одного слоя является входом для следующего слоя.

Архитектура нейронной сети в данном случае состоит из следующих слоев:

nn.Linear(1, 20): Линейный слой с входным размером 1 и выходным размером 20. Это означает, что данный слой принимает одномерный вектор размерностью 1 и выдает одномерный вектор размерностью 20, применяя линейное преобразование к входным данным.

nn.ReLU(): Функция активации ReLU (Rectified Linear Unit) применяется к выходу предыдущего слоя. ReLU пропускает положительные значения без изменений и отсекает отрицательные значения, заменяя их нулем.

nn.Linear(20, 10): Линейный слой с размерностью входа 20 и размерностью выхода 10. Аналогично первому линейному слою, производится линейное преобразование размерности входа в размерность выхода.

nn.Tanh(): Гиперболический тангенс (Tanh) применяется к выходу предыдущего слоя. Tanh сжимает значения в диапазоне от -1 до 1.

nn.Linear(10, 1): Линейный слой с размерностью входа 10 и размерностью выхода 1.

nn.Sigmoid(): Сигмоидная функция применяется к выходу предыдущего слоя. Сигмоид преобразует значения в диапазоне от 0 до 1.

Таким образом, данная строка кода определяет последовательную нейронную сеть с различными слоями и функциями активации, которая принимает одномерный вход и выдает одномерный выход. Каждый слой выполняет определенные математические операции и обеспечивает нелинейность в выходных данных посредством функций активации.

In [ ]:
NN = nn.Sequential(nn.Linear(1, 20),nn.ReLU(),nn.Linear(20, 10),nn.Tanh() , nn.Linear(10,1),nn.Sigmoid())
NN

Sequential(
  (0): Linear(in_features=1, out_features=20, bias=True)
  (1): ReLU()
  (2): Linear(in_features=20, out_features=10, bias=True)
  (3): Tanh()
  (4): Linear(in_features=10, out_features=1, bias=True)
  (5): Sigmoid()
)

Данная строка кода создает тензор X размером (1000, 1) с нормально распределенными случайными значениями.

Конкретнее, функция torch.normal() используется для генерации случайных чисел из нормального (гауссовского) распределения.

Аргумент mean задает среднее значение распределения. В данном случае, torch.zeros((1000, 1)) создает тензор размером (1000, 1), состоящий из нулей. Этот тензор задает среднее значение 0 для каждого элемента в тензоре X.

In [ ]:
X = torch.normal(mean= torch.zeros((1000, 1)), std= 2)

Данная строка кода применяет функцию косинуса (torch.cos()) к каждому элементу тензора X и сохраняет результаты в тензор Y.

В данном случае, тензор X содержит случайно сгенерированные значения, как описано в предыдущем вопросе. Функция torch.cos() вычисляет косинус для каждого элемента входного тензора.

In [ ]:
Y = torch.cos(X)

matplotlib.pyplot - это модуль библиотеки matplotlib, который предоставляет функциональность для создания различных типов графиков и диаграмм.

seaborn - это библиотека для визуализации, основанная на matplotlib. Она предоставляет более высокоуровневый интерфейс и более привлекательные стили по умолчанию для графиков.

sns.set_theme() - эта строка кода устанавливает текущую тему оформления seaborn для графиков. Темы оформления определяют внешний вид элементов графиков, таких как фоны, цвета и шрифты. Вызов функции set_theme() без аргументов устанавливает тему по умолчанию.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

Данная строка кода создает объект DataFrame из двух столбцов данных X и Y.

pd.DataFrame - это функция из библиотеки pandas, которая используется для создания объекта DataFrame. DataFrame - это двумерная структура данных, которая представляет собой таблицу с метками строк и столбцов.

{'X' : X.view(-1), 'Y' : Y.view(-1)} - это словарь, который передается в качестве аргумента для создания DataFrame. В словаре каждый ключ ('X' и 'Y') соответствует названию столбца, а значения (X.view(-1) и Y.view(-1)) представляют собой данные для этих столбцов. X.view(-1) и Y.view(-1) предполагает, что X и Y - это объекты с определенными размерностями, и view(-1) используется для приведения их к одной размерности.

Таким образом, data будет содержать DataFrame с двумя столбцами X и Y, где каждый столбец содержит соответствующие данные, переданные из X и

In [ ]:
data = pd.DataFrame({'X' : X.view(-1), 'Y' : Y.view(-1)})

In [ ]:
X_test  = torch.normal(mean= torch.zeros((100, 1)), std= 2)
Y_test = torch.cos(X_test)

Данная строчка кода выполняет следующее:

Использует модель нейронной сети NN для входного тестового набора данных X_test.

Применяет модель нейронной сети NN к тензору X_test и получает прогнозы Y_preds - выходные значения, предсказанные нейронной сетью для каждого входного примера в X_test.

В результате, Y_preds будет содержать прогнозы, сделанные моделью нейронной сети NN для входного тестового набора данных X_test.

In [ ]:
Y_preds = NN(X_test)

Данная строчка кода выполняет следующие действия:

Создает новый объект data3, который является пустым DataFrame (таблицей) в библиотеке pandas.

Заполняет столбец с названием 'Y' значениями из тензора Y_preds. Для этого используется метод detach(), который отсоединяет тензор Y_preds от графа вычислений. Затем применяется метод view(-1), который преобразует форму тензора в одномерную. В результате получается одномерный массив значений Y_preds, который становится столбцом 'Y' в data3.

Заполняет столбец с названием 'X' значениями из тензора X_test. Аналогично как в предыдущем шаге, сначала применяется метод detach() для отсоединения тензора X_test от графа вычислений, а затем метод view(-1) для преобразования формы в одномерный массив значений. Результатом будет одномерный массив значений X_test, который становится столбцом 'X' в data3.

Таким образом, data3 будет содержать два столбца: 'Y' со значениями прогнозов Y_preds и 'X' со значениями из X_test.

In [ ]:
data3 = pd.DataFrame({'Y' : Y_preds.detach().view(-1),'X' : X_test.detach().view(-1)})

Данный код выполняет следующие действия:

Создает объект criterion типа torch.nn.MSELoss(). MSELoss (Mean Squared Error Loss) является функцией потерь, которая используется для измерения разницы между предсказанными значениями и целевыми значениями в задачах регрессии. Она измеряет среднеквадратичную ошибку между предсказаниями и целевыми значениями.

Создает объект optimizer типа torch.optim.Adam(). Adam представляет собой оптимизационный алгоритм, используемый для обновления параметров модели во время обучения. В данном случае, NN.parameters() используется для передачи параметров нейронной сети NN в оптимизатор Adam. Параметр lr=1e-2 указывает скорость обучения (learning rate) оптимизатора, то есть шаг, с которым параметры модели будут обновляться в каждой итерации обучения.

Таким образом, criterion представляет функцию потерь (MSE Loss), а optimizer представляет оптимизатор (Adam), который будет использоваться для обучения нейронной сети NN с помощью градиентного спуска

In [ ]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(NN.parameters(), lr=1e-2)

Данный код представляет функцию train, которая выполняет обучение модели машинного обучения с помощью переданных параметров.

Аргументы функции:

model: модель машинного обучения, которую нужно обучить.
x и y: входные данные и соответствующие им целевые значения (метки).
criterion: функция потерь, которая будет использоваться для измерения разницы между предсказанными значениями и целевыми значениями.
optimizer: оптимизатор, используемый для обновления параметров модели.
num_epoch: количество эпох обучения (полных проходов по всем обучающим данным).
show_freq: частота вывода информации о потерях (loss) во время обучения. Значение по умолчанию равно 10, что означает, что информация о потерях будет выводиться каждые 10 эпох.
Внутри функции есть два цикла:

Внешний цикл for t in range(num_epoch) выполняет итерации по каждой эпохе обучения.
Внутренний цикл for X in x проходится по каждому входному примеру в обучающих данных x.
В каждой итерации внутреннего цикла:

Модель model принимает входной пример X и делает предсказание y_pred.
Вычисляется значение функции потерь loss между предсказанным значением y_pred и соответствующим целевым значением y[i].
Оптимизатор optimizer обнуляет градиенты предыдущего шага с помощью optimizer.zero_grad().
Вычисляется градиент функции потерь с помощью loss.backward().
Оптимизатор optimizer выполняет шаг градиентного спуска с помощью optimizer.step(), обновляя параметры модели на основе вычисленных градиентов.
После каждой show_freq эпох выводится значение последней потери (loss.item()).

В конце функция возвращает обученную модель model.

In [ ]:
def train(model, x,y,criterion, optimizer,num_epoch, show_freq = 10):
    for t in range(num_epoch):
        i = 0
        for X in x:
            y_pred = model(X)
            loss = criterion(y_pred, y[i])
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            i+=1
        if t % show_freq == 0:
            print(t, loss.item())
    return model

In [ ]:
NN = train(NN, X, Y,criterion,optimizer, 1, 1)

0 0.021843310445547104


In [ ]:
Y_preds = NN(X_test)

In [ ]:
data4 = pd.DataFrame({'Y' : Y_preds.detach().view(-1),'X' : X_test.detach().view(-1)})

In [ ]:
NN = train(NN, X, Y,criterion,optimizer, 15, 1)

0 3.228604327887297e-05
1 0.0015543471090495586
2 0.0003375062660779804
3 0.00024005769228097051
4 0.0009484472102485597
5 2.896690057241358e-05
6 0.004790817387402058
7 0.005243571009486914
8 1.61111220222665e-05
9 9.296193456975743e-05
10 0.00024980102898553014
11 0.005189491901546717
12 0.00035039993235841393
13 0.025938717648386955
14 0.0001791992544895038


Данный код определяет класс Net, который является подклассом nn.Module из библиотеки PyTorch. Класс Net представляет собой нейронную сеть с двумя полносвязными слоями.

В конструкторе __init__ класса Net определяются и инициализируются два полносвязных слоя: self.L1 и self.L2. Первый слой self.L1 имеет размерность dim на входе и 20 нейронов на выходе. Второй слой self.L2 имеет 20 нейронов на входе и 1 нейрон на выходе.

Метод forward класса Net определяет последовательность операций прямого прохода (forward pass) нейронной сети. Входной тензор x проходит через первый слой self.L1, затем применяется функция активации ReLU (F.relu), результат проходит через второй слой self.L2, и наконец, применяется функция активации сигмоида (torch.sigmoid), возвращая выходной тензор.

Таким образом, класс Net определяет архитектуру нейронной сети с двумя полносвязными слоями и описывает прямой проход для получения предсказаний на входных данных.

In [ ]:
class Net(nn.Module):

    def __init__(self, dim):
        super(Net, self).__init__()
        self.L1 = nn.Linear(dim, 20)
        self.L2 = nn.Linear(20,1)

    def forward(self, x):
        x = self.L1(x)
        x = F.relu(x)
        x = self.L2(x)
        x = torch.sigmoid(x)
        return x

Данный код использует модуль train_test_split из библиотеки scikit-learn (sklearn) для разделения данных на обучающий и тестовый наборы.

Сначала он импортирует функцию train_test_split из модуля sklearn.model_selection.

Затем он считывает данные из файла 'gbm-data.csv' с помощью библиотеки Pandas и сохраняет их в переменную data.

Далее, код создает две переменные: targets и features. Переменная targets содержит значения первого столбца данных (data.columns[0]), преобразованных в массив NumPy. Переменная features содержит значения всех столбцов, начиная со второго (data.columns[1:]), также преобразованных в массив NumPy.

Затем код вызывает функцию train_test_split и передает ей features, targets, test_size=0.8 (что означает, что 80% данных будут использованы для тестирования), и random_state=241 (задает начальное значение для генератора случайных чисел, чтобы гарантировать воспроизводимость результатов).

Результат вызова функции train_test_split - четыре набора данных: X_train, X_test, y_train и y_test. X_train содержит обучающие данные (80% от исходных данных), X_test содержит тестовые данные (20% от исходных данных), y_train содержит метки (целевые значения) для обучающих данных и y_test содержит метки для тестовых данных.

In [ ]:
from sklearn.model_selection import train_test_split

data = pd.read_csv('gbm-data.csv')
#print(data.columns)

targets = data[data.columns[0]].to_numpy()
features = data[data.columns[1:]].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(features, targets,test_size=0.8,random_state=241)

Данный код использует библиотеку PyTorch для преобразования данных в тензоры.

Сначала код преобразует переменные X_train и X_test из массивов NumPy в тензоры PyTorch, используя функцию torch.Tensor(). То же самое происходит с переменными y_train и y_test.

Преобразование данных в тензоры позволяет использовать данные в операциях, оптимизированных для работы с тензорами PyTorch. Тензоры являются основной структурой данных в PyTorch и обеспечивают эффективные вычисления для обучения нейронных сетей и других моделей глубокого обучения.

Преобразование данных в тензоры также может быть полезным при использовании других функций и операций, доступных в библиотеке PyTorch, таких как автоматическое дифференцирование и использование GPU для ускорения вычислений.

In [ ]:
X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)

y_train = torch.Tensor(y_train)
y_test = torch.Tensor(y_test)

In [ ]:
net = Net(1776)

Данный участок кода выполняет инициализацию функции потерь (loss function) и оптимизатора для обучения нейронной сети.

Строка criterion = torch.nn.BCELoss() создает экземпляр функции потерь с помощью torch.nn.BCELoss(). BCELoss означает "binary cross-entropy loss" и обычно используется в задачах классификации бинарных данных. Она вычисляет потерю между бинарными предсказаниями и соответствующими истинными метками.

Строка optimizer = torch.optim.Adam(net.parameters(), lr=1e-3) создает экземпляр оптимизатора Adam с помощью torch.optim.Adam(). Оптимизатор Adam используется для обновления весов модели во время обучения. Он принимает в качестве параметра net.parameters(), что означает, что все обучаемые параметры модели (веса и смещения) будут оптимизироваться. Параметр lr=1e-3 задает скорость обучения (learning rate) для оптимизации, то есть определяет, насколько сильно веса будут обновляться на каждой итерации обучения.

Эти две строки кода подготавливают необходимые компоненты для обучения нейронной сети: функцию потерь для оценки ошибки и оптимизатор для обновления весов модели при обратном распространении ошибки.

In [ ]:
criterion = torch.nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)

In [ ]:
net = train(net, X_train, y_train.view(750,1),criterion,optimizer, 15, 1)

Данный код использует нейронную сеть net для выполнения предсказаний на тестовых данных X_test.

Строка y_prob = net(X_test) прогоняет тестовые данные X_test через нейронную сеть net и сохраняет результаты предсказаний в y_prob. Результаты предсказаний обычно выражают вероятности принадлежности к определенным классам.

Строка (y_prob>0.5) сравнивает каждое предсказание из y_prob с пороговым значением 0.5. В результате получается булевский тензор, где True указывает на предсказание больше 0.5, а False указывает на предсказание меньше или равное 0.5.

Строка .detach().numpy() отвечает за отсоединение от вычислительного графа PyTorch и преобразование тензора y_prob в массив NumPy. Такое преобразование может быть полезным, если требуется использовать выходные данные вне фреймворка PyTorch.

Строка .astype('int32') приводит тип элементов массива NumPy к типу int32. В данном случае, вероятности классов преобразуются в целые числа.

Строка .reshape(-1) изменяет форму массива, чтобы привести его к одномерному массиву. В данном случае, это может быть полезным, если результаты предсказаний y_pred требуется использовать в дальнейших операциях или метриках.

В итоге, в переменной y_pred будет храниться одномерный массив из 0 и 1, где 0 указывает на предсказание меньше или равное 0.5, а 1 указывает на предсказание больше 0.5. Этот массив может использоваться для оценки качества предсказаний модели или других задач, связанных с классификацией.

In [ ]:
y_prob = net(X_test)
y_pred = (y_prob>0.5).detach().numpy().astype('int32').reshape(-1)

Данный код выполняет вычисление точности (accuracy) модели на основе предсказаний y_pred и истинных меток y_test.

Строка ans = y_test.detach().numpy().reshape(-1) отвечает за преобразование тензора y_test в массив NumPy и изменение его формы до одномерного массива. Предполагается, что y_test содержит истинные метки классов для тестовых данных.

Строка (y_pred == ans) сравнивает каждый элемент предсказаний y_pred с соответствующим элементом истинных меток ans. Результатом сравнения является булевский массив, где True указывает на правильное предсказание, а False указывает на неправильное предсказание.

Строка .astype('int32') преобразует булевский массив в массив целых чисел типа int32, где True преобразуется в 1, а False в 0. Таким образом, каждое правильное предсказание будет представляться значением 1, а неправильное - значением 0.

Строка .sum() вычисляет сумму всех элементов массива, то есть подсчитывает количество правильных предсказаний.

Выражение len(y_pred) возвращает количество элементов в массиве y_pred, которое представляет общее число предсказаний.

Наконец, acc = (y_pred == ans).astype('int32').sum()/len(y_pred) вычисляет точность (accuracy) модели путем деления количества правильных предсказаний на общее число предсказаний. Результат сохраняется в переменной acc.

In [ ]:
ans = y_test.detach().numpy().reshape(-1)
acc = (y_pred == ans).astype('int32').sum()/len(y_pred)

Данный код представляет функцию train, которая выполняет обучение модели машинного обучения.

Входные параметры функции:

model: модель, которую нужно обучить.
x: входные данные (значения признаков).
y: целевые метки (истинные значения, которые модель должна предсказывать).
criterion: функция потерь (loss function), которая используется для оценки ошибки модели.
optimizer: оптимизатор, используемый для обновления параметров модели на основе градиентного спуска.
num_epoch: количество эпох обучения, то есть сколько раз модель пройдет по всем обучающим примерам.
show_freq: частота вывода информации о потерях (losses) на каждой эпохе. По умолчанию равно 10, что означает вывод информации каждые 10 эпох.
Внутри функции происходит итерация по числу эпох num_epoch. Затем для каждой эпохи итерируется по всем обучающим примерам X из входных данных x. Для каждого обучающего примера происходит следующее:

На основе текущего обучающего примера X, модель model делает предсказание y_pred.
Вычисляется значение функции потерь loss между предсказанными значениями y_pred и истинными метками y[i].
Оптимизатор optimizer зануляет градиенты ранее вычисленных параметров модели.
Вызывается метод backward() у loss для вычисления градиентов функции потерь по параметрам модели.
Оптимизатор optimizer обновляет параметры модели на основе вычисленных градиентов с помощью метода step().
Индекс i увеличивается для обработки следующего обучающего примера.
Если значение текущей эпохи t делится на show_freq без остатка, то происходит вывод значения текущей потери loss.item(). Значение потери добавляется в список losses на каждой эпохе.

В конце функция возвращает обученную модель model и список значений потерь losses.

In [ ]:
def train(model, x,y,criterion, optimizer,num_epoch, show_freq = 10):
    losses = []
    for t in range(num_epoch):
        i = 0
        for X in x:
            y_pred = model(X)
            loss = criterion(y_pred, y[i])
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            i+=1
        if t % show_freq == 0:
            print(t, loss.item())
        losses.append(loss.item())
    return model, losses

In [ ]:
net1 = Net(1776)
criterion = torch.nn.BCELoss()
optimizer = torch.optim.Adam(net1.parameters(), lr=1e-2)
net1,loss = train(net1, X_train, y_train.view(750,1),criterion,optimizer, 15, 1)

In [ ]:
def train(model, x,y,x_test,y_test,criterion, optimizer,num_epoch, show_freq = 10):
    losses = []
    val_losses = []
    for t in range(num_epoch):
        i = 0
        for X in x:
            y_pred = model(X)
            loss = criterion(y_pred, y[i])
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            i+=1
        if t % show_freq == 0:
            print(t, loss.item())
        losses.append(loss.item())
        with torch.no_grad():
            y_val = model(x_test)
            loss_al = criterion(y_val, y_test)
            val_losses.append(loss_al)
    return model, losses,val_losses

In [ ]:
net2 = Net(1776)

In [ ]:
criterion = torch.nn.BCELoss()
optimizer = torch.optim.Adam(net2.parameters(), lr=1e-2)

In [ ]:
net2,loss,val = train(net2, X_train, y_train.view(750,1),X_test,y_test.view(3001,1),criterion,optimizer, 15, 1)